# -*- coding: utf-8 -*-

version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            -echo "Installing dependencies..."
            -pip install  r requirement.txt -t lib
    build:
        commands:
            -echo "Zipping deployement package..."
            -cd lib
            -zip -r9 ../deployment_package.zip .
            -cd ..
            -zip -g  deployment_package.zip lambda_function.py
    post_build:
        commands:
            -echo "Updating lambda function.."
            -aws lambda update -function-code  --function-name lambda-github --zip-file fileb://deployment_package.zip
            -echo "DONE!!"
